# This stack uses values from .env
# Copy .env.example to .env and edit for your system
networks:
  backend:
    driver: bridge

services:
  crafty:
    container_name: crafty_controller
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    ports:
      - "8443:8443"
      - "8124:8124"
      - "19132-19140:19132-19140/udp"
      - "25565-25575:25565-25575"
    networks:
      - backend
    volumes:
      - /home/owlburtoe/docker/crafty/backups:/crafty/backups
      - /home/owlburtoe/docker/crafty/logs:/crafty/logs
      - /home/owlburtoe/docker/crafty/servers:/crafty/servers
      - /home/owlburtoe/docker/crafty/config:/crafty/app/config
      - /home/owlburtoe/docker/crafty/import:/crafty/import
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "--no-check-certificate",
          "https://crafty:8443/api/v2",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  discord-bot:
    container_name: mc_discord_bot
    image: ghcr.io/owlburtoe/mc-discord-bot:main
    env_file: .env
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "8085:8080"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
